Add pushbullet service
kha7iq/pingme pull request #7
Opened 2021-04-15 19:10 UTC by versus

Added a pushbullet service  (pushbullet.com)

2021-04-21 06:25 UTC, kha7iq commented
Hello @versus Thank you for your contribution great work done.
The library also support SMS with push bullet, can you try to include that.
It will be great to have SMS support with push bullet.
You can use a boolean flag with the cli, for example
```
ping pushbullet --sms true
```
What are your thoughts on this.
Let me know if there is anything i can help with.

2021-04-23 09:58 UTC, versus commented
Hello @kha7iq,  I tried doing it before.  
Unfortunately, It doesn't work on my android devices :-(
Maybe,  you can do it,  there is a docs page: https://help.pushbullet.com/articles/how-do-i-send-text-messages-from-my-computer/

I just send alert SMS from opsengine.
By the way,  I think about adding modules for pageduty and opsengine to pingme.

Thanks for awesome tool PingMe. I like to use it.

2021-04-23 14:34 UTC, kha7iq reviewed
let me know if you need some explanation about this.
Please pull the changes from master first and then make the pull request.
I will create an issue for this you can link in pull request

2021-04-23 14:34 UTC, kha7iq commented on cmd/pushbullet.go
> +	Device  string
```
type pushBullet struct {
	Token   string
	Message string
	Title   string
	Device  string
	PhoneNumber string
	SMS bool
}
```
# You an add phone number and SMS boolean flag

2021-04-23 14:35 UTC, kha7iq commented on cmd/pushbullet.go
> +}
```
Action: func(ctx *cli.Context) error {
			notifier := notify.New()

			switch pushBulletOpts.SMS {
			case true:
			pushBulletSmsSvc, err := pushbullet.NewSMS(pushBulletOpts.Token, pushBulletOpts.Device)
			if err != nil {
				return err
			}
				devices := strings.Split(pushBulletOpts.PhoneNumber, ",")
				for _, v := range devices {
					if len(v) <= 0 {
						return fmt.Errorf(EmptyChannel)
					}
				pushBulletSmsSvc.AddReceivers(v)

					notifier.UseServices(pushBulletSmsSvc)

					if err := notifier.Send(
						context.Background(),
						pushBulletOpts.Title,
						pushBulletOpts.Message,
					); err != nil {
						return err
					}

				}
			default:
				pushBulletSvc := pushbullet.New(pushBulletOpts.Token)

				devices := strings.Split(pushBulletOpts.Device, ",")
				for _, v := range devices {
					if len(v) <= 0 {
						return fmt.Errorf(EmptyChannel)
					}
					pushBulletSvc.AddReceivers(v)
				}

				notifier.UseServices(pushBulletSvc)

				if err := notifier.Send(
					context.Background(),
					pushBulletOpts.Title,
					pushBulletOpts.Message,
				); err != nil {
					return err
				}

			}

			log.Println("Successfully sent!")
			return nil
		},
	}
}
```

2021-04-23 14:36 UTC, kha7iq commented on cmd/pushbullet.go
> +			},
```
	&cli.BoolFlag{
				Destination: &pushBulletOpts.SMS,
				Name:        "sms",
				Value:       false,
				Usage:       "To send sms message set the value to 'true'",
				EnvVars:     []string{"PUSHBULLET_SMS"},
			},
		},

&cli.StringFlag{
				Destination: &pushBulletOpts.PhoneNumber,
				Name:        "number",
				Aliases:     []string{"n"},
				Usage:       "Device's nickname of pushbullet.",
				EnvVars:     []string{"PUSHBULLET_NUMBER"},
			},
```

2021-04-23 14:37 UTC, kha7iq requested changes
these changes are required to send sms with a boolean flag

2021-04-26 09:15 UTC, kha7iq commented
@ Do let me know today , if you can include these change, if no can you please pull the changes from master before making the pull request so that i can merge existing contribution and include the rest my self.

2021-04-27 16:31 UTC, kha7iq commented
Closing this as stale, i will include you contribution and open a separate PR

2021-04-27 16:31 UTC, closed without merging